### ISSUE TITLE
Feature request: save the whole page, at least the images

### ISSUE THREAD

**Issue by helmut72** [go-shiori/shiori#108]
Would be nice to replace Pocket with Shiori. Thank you.

**Comment by RadhiFadlillah** [comment]
Since the ramadhan branch has been merged, Shiori now support archiving an entire web page for offline use :

![Archival support](https://user-images.githubusercontent.com/6129042/63772244-e45e1780-c902-11e9-93e9-d406a26b2702.png)

When the archive exists, Shiori will use it to serve image, audio and video (when possible of course). For example, when using reader mode, all image is loaded from our local server :

![No exxternal network used](https://user-images.githubusercontent.com/6129042/63772542-782fe380-c903-11e9-88f0-d7eaf228b332.png)

With that said, I believe this feature has been implemented so I will close it for now. Feel free to reopen it if needed.
