### ISSUE TITLE
Group untagged bookmarks

### ISSUE THREAD

**Issue by dpffxhad** [go-shiori/shiori#109]

**Comment by RadhiFadlillah** [comment]
Since the ramadhan branch has been merged, now Shiori can group the tagged and untagged  bookmarks :

![Add new menu for untagged](https://user-images.githubusercontent.com/6129042/63772778-0310de00-c904-11e9-8e95-292b5c17cd78.png)

With that said, this feature has been implemented so I will close it for now. Feel free to reopen it if needed.
