### ISSUE TITLE
Feature request: Infinite Scrolling

### ISSUE THREAD

**Issue by dpffxhad** [go-shiori/shiori#115]

**Comment by saesh** [comment]
Hey @dpffxhad, you can add more accounts with the `shiori account add <name>` command. See [the wiki](https://github.com/RadhiFadlillah/shiori/wiki/Usage) for more information.

Is this issue resolved for you and can be closed?

**Comment by dpffxhad** [comment]
@saesh You totally misunderstood my question. I was hoping to have infinite scrolling home (like twitter) instead of pagination.

**Comment by RadhiFadlillah** [comment]
Hi @dpffxhad

Unfortunately, I don't really like endless scrolls, because :

- Endless scrolls make browser's scrollbar unusable and untrustworthy.
- Huge memory usage, especially if there are many item to load. And it seems to be the case for several people that have thousands bookmarks in their database.
- It's quite hard to implement.

With that said, I don't think I will do this.
