### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by rain-1** [go-shiori/shiori#116]
Hello. I can't install it, this is the error:

```
$ go get -u github.com/RadhiFadlillah/shiori
# cd /home/www/go/src/github.com/RadhiFadlillah/shiori/readability; git pull --ff-only
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

package github.com/RadhiFadlillah/shiori/readability: exit status 1
```

**Comment by saesh** [comment]
Hey @rain-1 this is because the shiori git repository uses [a submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules).

Is this issue resolved for you and can be closed?

**Comment by rain-1** [comment]
it's not resolved. The 'go' tool is not able to build and install this software.

you can close it if you are OK with that.

**Comment by RadhiFadlillah** [comment]
Since the ramadhan branch is merged, this issue should be fixed now. I agree the Git submodules is not really suitable for Go. Fortunately Go 1.11 brings modules support, which mean now we can stop using git submodules.

With that said, now Shiori is installabe via `go get` so I will close this issue. Feels free to reopen it if this issue still exists.
