### ISSUE TITLE
"Too Many Requests" when bookmarking Reddit links

### ISSUE THREAD

**Issue by disposedtrolley** [go-shiori/shiori#127]
When attempting to bookmark a Reddit link, shiori is immediately blocked and a "Too Many Requests" error is returned, shown below.

![Screenshot from 2019-04-07 10-55-50](https://user-images.githubusercontent.com/4476568/55677088-08559800-5925-11e9-84a3-58e320fdb444.png)

It appears that Reddit is taking measures to prevent content from being scraped, and the workaround is to set a custom `user-agent` header for any requests destined for Reddit - https://www.reddit.com/r/redditdev/comments/3qbll8/429_too_many_requests/

One possible solution might be to feed the PID or Docker container ID into the `readability` module to be set as part of the `user-agent` header. This way each instance of shiori is identified separately which should prevent any rate limiting.

**Comment by RadhiFadlillah** [comment]
Since the ramadhan branch is merged, this issue should be fixed now. Now Shiori uses its own user agent :

```
User-Agent: Shiori/2.0.0 (+https://github.com/go-shiori/shiori)
```

Now it should works fine as can be seen in [screenshot](https://raw.githubusercontent.com/go-shiori/shiori/master/docs/cover.png) on readme.

With that said, I will close this issue for now. Feel free to reopen it if needed.
