### ISSUE TITLE
Show URL in the web-interface

### ISSUE THREAD

**Issue by hoijui** [go-shiori/shiori#130]
In the GUI (web-interface) I can see the domain in the "wall", and when editing a bookmark I can see neither domain nor the full URL. Why so?
Is it a design-choice not to show the URL?
In the case of broken links, it is especially frustrating, because the only way to get to the URL, is to use the CLI.

Thank you for shiori! I had a thorough look through [this list of self-hostable bookmark software](https://github.com/Kickball/awesome-selfhosted#bookmarks-and-link-sharing), and finally decided to use yours. :-)

**Comment by demlak** [comment]
this topic is more about editing web url. but  +1 from me =)

**Comment by RadhiFadlillah** [comment]
Since the ramadhan branch has been merged, this feature has been implemented. Now we can edit the URL from web interface :

![edit-url](https://user-images.githubusercontent.com/6129042/63777835-04470880-c90e-11e9-9190-25b083881feb.png)

Since it has been implemented, I will close this issue for now. Feel free to reopen it if needed.

**Comment by hoijui** [comment]
ole! :-)
