### ISSUE TITLE
BUG: Tag Suggestions in mobile View problem

### ISSUE THREAD

**Issue by demlak** [go-shiori/shiori#138]
When i want to select tag suggstions on my Mobile-Firefox, the keyboard looses focus and it the site dimensions shoved down. so the dimensions are wrong to select the suggestions.. and so on and on..

tag suggestions in mobile View are nearly unusable

#33

**Comment by RadhiFadlillah** [comment]
Actually, the suggestion is not clickable at all :smile:

The suggestion is actually just a simple tooltip. When the user agree with suggestion, he only need to press enter, then the suggestion in tooltip will be put in the text box. This is why when you try to click or touch the suggestion, the focus is changed from text box into the tooltip. This is also why there is only one suggestion available at any time.

Sure, ideally the suggestion is clickable. However I found it too hard to do and it increase too much complexity for such a small feature, so I decided to keep it as it is. Besides, since we only need to click enter, we can keep our focus on keyboard instead of click/touching the suggestion so I kinda like it.

With that said, I don't think I will change it, so I will close it for now.
