### ISSUE TITLE
Feature request: Markdown or similar file system database

### ISSUE THREAD

**Issue by braderhart** [go-shiori/shiori#144]
I really like the idea of using a took like Shiori for bookmarks, but I would really like the option to organize and manage my bookmarks locally from the file system as well. Would really nice to see the option to create folders, and add files for each bookmark that can be managed via Shiori. Here is an example:

https://gohugo.io/content-management/front-matter/

**Comment by RadhiFadlillah** [comment]
Hi @braderhart, unfortunately I don't think I will add additional database system. 

Right now Shiori already supports MySQL and SQLite, and to be honest it's already quite hard to make sure Shiori works properly with those two. The silver lining is both of them use similar SQL syntax which make them share a lot of codes.

I'm worried if I add additional database system I won't be able to make it work properly, especially since Shiori doesn't have any unit tests right now :disappointed:
