### ISSUE TITLE
ability to edit the old url's?

### ISSUE THREAD

**Issue by thepenguinthatwants** [go-shiori/shiori#148]
I sometimes update certain url's but seems like Shiori is unable to edit a URL once entered.

**Comment by RadhiFadlillah** [comment]
Hi @thepenguinthatwants, edit URL is supported in latest version of Shiori.

From cli you can use `--url` flag in `update` command like this :

```
shiori update --url http://example.com 123
```

In web interface you can modify the URL in edit dialog :

![Screenshot_2019-09-05 Shiori - Bookmarks Manager](https://user-images.githubusercontent.com/6129042/64318348-0b43da00-cfe4-11e9-8fed-62eefd1274c3.png)

**Comment by thepenguinthatwants** [comment]
Hi!

Oh cool.

I am using the docker image and it hadn't this feature yet.

**Comment by RadhiFadlillah** [comment]
@thepenguinthatwants yeah, I haven't updated the docker image in a while.

I will try to update docker image ASAP.

**Comment by thepenguinthatwants** [comment]
Thanks!

There are quite many that uses the docker image. Really thankful that about this application.

**Comment by RadhiFadlillah** [comment]
Hi @thepenguinthatwants, the Docker image has been updated and can be pulled by running :

```
docker pull radhifadlillah/shiori
```

**Comment by thepenguinthatwants** [comment]
Hi!
Thanks it looks good. But how to edit entries?  I cant see any options or clickable things for editing the information? Feels like all I can do is about opening the url.

**Comment by thepenguinthatwants** [comment]
Actually after the update it seems like my user has lost all the rights?

**Comment by hoijui** [comment]
same here

**Comment by RadhiFadlillah** [comment]
@thepenguinthatwants @hoijui I'm so sorry for the trouble :disappointed: 

This issue happened because in Shiori v1.0.0 there are no account level, which means everyone is treated as owner. However, Shiori v1.5.0 has two account level i.e. owner and visitor. The level difference is stored in database as boolean value in column `owner` with default value `false` (which means by default all account is visitor, unless specified otherwise)

https://github.com/go-shiori/shiori/blob/89aad30a177a512ef3984699202c26d8c5cd1f89/internal/database/sqlite.go#L41-L48

Because in v1.5.0 by default all account is visitor, when updating from v1.0 to v1.5 all of the old accounts by default will be marked as visitor. Fortunately, when there are no `owner` registered in database, we can login as owner using default account :

```
username: shiori
password: gopher
```

So, as workaround for this issue, you should :

- Login as default account.
- Go to options page.
- Remove your old accounts.
- Recreate them, but now as owner.

![bug-2019-09-22_15 39 13](https://user-images.githubusercontent.com/6129042/65384738-fab79180-dd4f-11e9-9838-72ca840b6e97.gif)

**Comment by thepenguinthatwants** [comment]
So existing users cant be changed into admins?

Also is it possible to delete the shiori account?

**Comment by RadhiFadlillah** [comment]
> So existing users cant be changed into admins?

Yeah, for now I haven't add the menu to change account level, so the workaround is delete it then create a new one with same name.

> Also is it possible to delete the shiori account?

The `shiori` account will be disabled once there is at least one owner account registered in database, as can be seen in these [lines](https://github.com/go-shiori/shiori/blob/fbd4e376435831316aee7fa890e58e7e9d1816f6/internal/webserver/handler-api.go#L76-L91).

**Comment by RadhiFadlillah** [comment]
Since it seems this issue has been solved, I will close it. Feel free to reopen it if needed.
