### ISSUE TITLE
Add support for dealing with cookie popups

### ISSUE THREAD

**Issue by KoenDG** [go-shiori/shiori#154]
Just adding this for the sake of the issue existing.

Lots of websites won't let you use their site if you don't first indicate your preferences via a popup.

If you try to bookmark/archive such a page, it will take the content of that interface, not the page lying behind it.

I wouldn't know how to deal with it and I don't know golang... but it sure is an issue.

**Comment by RadhiFadlillah** [comment]
Hi @KoenDG, could you give me an example URL to test ? 

I've tested it in several websites which ask cookies and Shiori works fine.

**Comment by KoenDG** [comment]
I ran into it on this site:

https://www.hln.be/

It's in dutch, red button on the left is the "continue" so to speak

**Comment by dav-m85** [comment]
Hi @KoenDG, I might be of some help here. From my knowledge (I work in a company actually selling such a GDPR banner), it is not easy feat to discard those in a consistent manner across all sites where they appear: each vendor has its own API and UX to do so ([there's over an hundred CMPs](https://advertisingconsent.eu/cmp-list/)), and nonetheless it would be bad if you could manage to do so (legal reasons).

If like me you're using the browser extension, a workaround might exist: instead of relying on the shiori server to fetch the html page (and get stuck with the GDPR banner), we could instead send the raw html shown in the browser for Shiori to archive. This way, the red button clicking AI would be... you :)

**Comment by RadhiFadlillah** [comment]
Hi guys,

Unfortunately, as @dav-m85 said, it seems impossible to do, both from technical and legal reasons. So the only workaround is to use the web extension.

In case you are using Chrome, I [haven't](https://github.com/go-shiori/shiori-web-ext/issues/3) build the extension there but hopefully it will be done soon.
