### ISSUE TITLE
Wiki improvement: Build from source

### ISSUE THREAD

**Issue by 0xsuid** [go-shiori/shiori#157]
Hello,

I've added **Cross Compiling For Windows** section in wiki.

I think you should add section for **building linux i386 binaries** or you should build and add it in release.

**Comment by RadhiFadlillah** [comment]
@0xsuid thanks for the wiki. However, IMHO cross compiling process shouldn't put in Installation page because that page is used by ordinary user who only want to run the app, which usually doesn't really care about how the app is cross-compiled. I put it under [FAQ](https://github.com/go-shiori/shiori/wiki/Frequently-Asked-Question#how-to-cross-compile-from-linux-to-windows-) which in my opinion is better and less intimidating.

> I think you should add section for building linux i386 binaries or you should build and add it in release.

Done.
