### ISSUE TITLE
MySQL column definitions are incorrect

### ISSUE THREAD

**Issue by deanishe** [go-shiori/shiori#163]
- `AUTO_INCREMENT` is missing on `id` fields
- `TEXT` fields must be truncated for use in an index
- `TEXT`/`BLOB` default values must be expressions

**Comment by RadhiFadlillah** [comment]
Hi @deanishe, thanks for the PR.

- I didn't make `id` field auto incremented because the ID will always be generated manually beforehand. However I guess it's fine to add it.
- I didn't know `TEXT` fields must have specific length when indexed, so thanks for this. For future visitor, this can be found in [MySQL](https://dev.mysql.com/doc/refman/5.7/en/blob.html) documentation :

   ```
   For indexes on BLOB and TEXT columns, you must specify an index prefix length.
   ```

   And in [MariaDB](https://mariadb.com/kb/en/library/text/) documentation :

   ```
   TEXT columns can only be indexed over a specified length. 
   ```

- Could you give me the documentation about `TEXT` default values must be expressions ? In MySQL it simply said :

   ```
   BLOB and TEXT columns cannot have DEFAULT values.
   ```

   While in MariaDB it said :

   ```
   Before MariaDB 10.2.1, BLOB and TEXT columns could not be assigned a DEFAULT value. 
   This restriction was lifted in MariaDB 10.2.1.
   ```

**Comment by deanishe** [comment]
> I didn't make id field auto incremented because the ID will always be generated manually beforehand

It threw an error when I tried to add a user. I figured `AUTO_INCREMENT` was the easiest way to solve that.

> Could you give me the documentation about TEXT default values must be expressions ?

https://dev.mysql.com/doc/refman/8.0/en/data-type-defaults.html#data-types-defaults-explicit

**Comment by RadhiFadlillah** [comment]
Thanks, now the PR has been merged.

> It threw an error when I tried to add a user. I figured `AUTO_INCREMENT` was the easiest way to solve that.

Oh boy, I really need to make unit tests ASAP.

**Comment by querwurzel** [comment]
Still doesn't work for me for MySQL 5.7 .. as you already stated BLOB and TEXT must not have default values. I may create a PR for that matter. Still wondering if I'm the only MySQL user here ..
