### ISSUE TITLE
Error adding https://waitbutwhy.com/2019/08/story-intro.html as a bookmark

### ISSUE THREAD

**Issue by timshannon** [go-shiori/shiori#188]
Error adding https://waitbutwhy.com/2019/08/story-intro.html as a bookmark:

```
failed to save bookmark: Error 1366: Incorrect string value: '\xE2\x86\x92' for column `shiori`.`bookmark`.`author` at row 1 (500)
```

**Comment by RadhiFadlillah** [comment]
@timshannon hey, that's weird. May I know which database that you use ?

**Comment by timshannon** [comment]
mariadb 10.4.6.

I'll try to spin up a sqlite instance in docker and get back to you to see if I can replicate it there.

**Comment by timshannon** [comment]
Yeah works fine with sqlite.

**Comment by RadhiFadlillah** [comment]
In my machine it works properly both in SQLite and MariaDB :

![Screenshot_2019-10-03 Shiori - Bookmarks Manager](https://user-images.githubusercontent.com/6129042/66131565-d6946400-e61d-11e9-92f1-d1b427f45ea5.png)

From the error message, it seems this issue is happened because your MariaDB doesn't support unicode icon `→`. This might be happened because the character encoding in your MariaDB server is set to `utf8` (which [doesn't](https://medium.com/@adamhooper/in-mysql-never-use-utf8-use-utf8mb4-11761243e434) support [emoticon](https://mathiasbynens.be/notes/mysql-utf8mb4)) instead of `utf8mb4`.

**Comment by timshannon** [comment]
So I'm just using the base mariadb image, you might want to consider forcing the character set and collation on database creation?

**Comment by timshannon** [comment]
For future reference for anyone else who runs into this, I got it working by switching the character set on the bookmarks table:

```sql
ALTER TABLE bookmark
 CONVERT TO CHARACTER SET utf8mb4;
```

Although you might want to do this on all tables.

**Comment by RadhiFadlillah** [comment]
> So I'm just using the base mariadb image, you might want to consider forcing the character set and collation on database creation?

Done in [a4dd1c8 ](https://github.com/go-shiori/shiori/commit/a4dd1c86874d32e10cca566b7fd3caa5e7b41ae3).

**Comment by deanishe** [comment]
Changing the charset in the database wasn't enough for me. I had to specify the charset on the MySQL connection, too. I've added that in PR #223
