### ISSUE TITLE
Archiving images fails on some URLs

### ISSUE THREAD

**Issue by tomas** [go-shiori/shiori#193]
For some reason when adding [this url](http://www.extentofthejam.com/pseudo/) with the "Archive" option set to true it doesn't store the images. Looks like the server disallows hotlinking, so that may be the issue (havent tested though).

![image](https://user-images.githubusercontent.com/10574/66332895-2c158d00-e90c-11e9-9db1-7fd10b7a23d0.png)

**Comment by RadhiFadlillah** [comment]
Hi @tomas 

This should be fixed by commit [a3e156](https://github.com/go-shiori/shiori/commit/a3e1563dff7aeaba97c3984fc7a3bd66743423eb) thanks to the new [web archiver](https://github.com/go-shiori/warc). I also added [fix](https://github.com/go-shiori/shiori/commit/0bc1b4a4cc39426769c07e3b69b2d1e568882a63) to make sure archive rendered as UTF-8.

![Screenshot_2019-10-09_21-02-59](https://user-images.githubusercontent.com/6129042/66488554-4c924280-ead8-11e9-87d0-efdd596bc0ee.png)

**Comment by RadhiFadlillah** [comment]
Since this issue should've been fixed now, I will close this issue. Feel free to reopen it if needed.
