### ISSUE TITLE
Clone Pocket API?

### ISSUE THREAD

**Issue by eabra** [go-shiori/shiori#208]
Would it be possible to offer a clone of the Pocket API so other Tools could connect and add/remove items here?

**Comment by 8bitgentleman** [comment]
Shiori already has an API, not as robust as Pocket's obviously but it lets you add/edit/remove bookmarks among other things

**Comment by khoanguyen96** [comment]
what other tools did you have in mind? just curious

**Comment by eabra** [comment]
Oh there are so many: miniflux, Reeder, self built tools, etc.

**Comment by 8bitgentleman** [comment]
All those tools are rss readers. Are you really looking for shiori to publish a user's saved links as a private rss feed?

**Comment by eabra** [comment]
No I'm looking for a way to have the RSS readers send the links to shiori without having to build new API integrations for it but instead utilize the cloned pocket API so they won't have to modify their applications this way.

**Comment by deanishe** [comment]
> No I'm looking for a way to have the RSS readers send the links to shiori without having to build new API integrations

Pretty much pointless, tbh. Even if an app isn't using the Pocket SDK, the API is still based on OAuth (which is large and complex) and every app will have its own consumer key and the Pocket API URL hardcoded.

As a result, adding support for a clone of the Pocket API is actually much more complicated than adding support for an entirely different, but much simpler, API.

Either way, I just don't see many (if any) app developers buying into it.

The "Share" menu would be a far better starting point for integration, imo, because it doesn't rely on application developers to modify their apps.

**Comment by samuelstevens** [comment]
> All those tools are rss readers. Are you really looking for shiori to publish a user's saved links as a private rss feed?

Sorry to open a dead issue two years later, but this is exactly what I'm looking for. I'd like to save links to a self-hosted service and then subscribe to a list of those links with a third-party rss reader. Is this possible?

**Comment by fmartingr** [comment]
> Sorry to open a dead issue two years later, but this is exactly what I'm looking for. I'd like to save links to a self-hosted service and then subscribe to a list of those links with a third-party rss reader. Is this possible?

This is not integrated withing shiori (and probably never will), but creating an RSS feed from the [Get Bookmarks](https://github.com/go-shiori/shiori/wiki/API#get-bookmarks) endpoint using your preferred fields should be trivial.

**Comment by samuelstevens** [comment]
Thanks! One thing that I find really exciting about Shiori is automatic content extraction. I looked through the API docs and couldn't see anyway to get that content via the API; did I miss something? Or should I fork/open a PR if I want to see that in Shiori?

**Comment by fmartingr** [comment]
> Thanks! One thing that I find really exciting about Shiori is automatic content extraction. I looked through the API docs and couldn't see anyway to get that content via the API; did I miss something? Or should I fork/open a PR if I want to see that in Shiori?

You're right! Content is not exposed through the API :(

Right now I could see this in two ways, either a new `/content/:id` endpoint to extract the content of a specific bookmark or a parameter in the `/bookmarks` endpoint to specify if we want the content extracted as well in the output.

I'd prefer the first one, I'm not very fond of parameters modifying an API response and the performance will dimisish the more bookmarks a database has; even if right now the `/bookmarks` performs a `JOIN` with the content table, this won't be like that in the future due to performance issues. (sqlite: #387)

What do you think?

**Comment by samuelstevens** [comment]
I prefer the first approach as well. 

I will take a look and see if I can implement a first pass sometime this week. Are there docs for contributing/developers?

**Comment by fmartingr** [comment]
> I prefer the first approach as well.
> 
> I will take a look and see if I can implement a first pass sometime this week. Are there docs for contributing/developers?

Right now there isn't much, everything available is in the wiki, though starting working on shiori should be much of a trouble if you have go installed. A Simple `go run main.go` should suffice. Keep in mind that if you use shiori on your computer directy this will load the same database, you can change it using [environment variables](https://github.com/go-shiori/shiori/wiki/Configuration). There's also a modd file included in the repository which bundles the assets and launches the development server, but it didn't work for me so I do the manual way.

One of the things I need to work on is updating the documentation (and moving it to the repository #394). I may overhaul how to work locally with shiori while doing that. Any feedback on that regard will be appreciated.
