### ISSUE TITLE
docker doesn't compile correctly or build when pulling from master

### ISSUE THREAD

**Issue by symgryph** [go-shiori/shiori#263]
I tried using the dockerfile, system crashes with the following:

github.com/lib/pq/scram
github.com/go-shiori/shiori/internal/core
github.com/lib/pq
github.com/mattn/go-sqlite3
github.com/shurcooL/httpfs/vfsutil
github.com/shurcooL/vfsgen
github.com/go-shiori/shiori/internal/webserver
github.com/spf13/cobra
github.com/go-shiori/shiori/internal/cmd
# github.com/go-shiori/shiori/internal/cmd
src/github.com/go-shiori/shiori/internal/cmd/root.go:93:32: too many arguments in call to gap.NewScope
        have (gap.ScopeType, string, string)
        want (gap.ScopeType, string)
src/github.com/go-shiori/shiori/internal/cmd/root.go:94:27: userScope.DataDir undefined (type *gap.Scope has no field or method DataDir)

**Comment by lapwat** [comment]
This is because of this line:

https://github.com/go-shiori/shiori/blob/b7a5a61e011e5613984043d55125aa4b33c7e7ea/internal/cmd/root.go#L93

The `apppaths` variable is of type `Scope`. This type was imported from `https://github.com/muesli/go-app-paths`

The `NewScope` signature has "recently" changed: https://github.com/muesli/go-app-paths/commit/549218f8b8d039b96fae900db39f1c1e737d45da#diff-d44c7badbd1491a3c4c5bbaf9f55d173

**Comment by lapwat** [comment]
Also, DataDir got replaced by DataDirs returning a prioritized list of data directories

See changelog here: https://github.com/muesli/go-app-paths/releases/tag/v0.2.0

**Comment by lapwat** [comment]
Please accept the pull request: https://github.com/go-shiori/shiori/pull/264

**Comment by fmartingr** [comment]
This is currently working (thanks for your PR) and we're planning changes in #278 and #341 as well. We will need a dependency update after that.
