### ISSUE TITLE
Link breaks after saving

### ISSUE THREAD

**Issue by GamerBS** [go-shiori/shiori#409]
When I try to save the link in the following example the link doesn't work anymore because an equal sign is added to the end. When I try to delete the equal sign it just gets added automatically again.
Example:
Trying to save:
https://comicforum.de/showthread.php?157893-Zensur-in-deutschen-Mangaver%C3%B6ffentlichungen

Actually being saved:
https://comicforum.de/showthread.php?157893-Zensur-in-deutschen-Mangaver%C3%B6ffentlichungen=

Shiori Version: 1.5.2

**Comment by fmartingr** [comment]
Hey @GamerBS I've successfully reproduced this issue and a fix is underway. Thanks for reporting it! 

Keep in mind that this is just a workaround because server side should behave the same even which the trailing equal sign, but well... 

This was happening when rebuilding the URL after removing `utm_` social associated parameters [here](https://github.com/go-shiori/shiori/blob/master/internal/core/url.go)

Relates to: https://github.com/golang/go/issues/20820

**Comment by GamerBS** [comment]
Thank you for your fast help.
