### ISSUE TITLE
REST API and Browser extension integration

### ISSUE THREAD

**Issue by julianxhokaxhiu** [go-shiori/shiori#41]
Hi,

I was also considering look at your product that you could consider adding a REST API that could be used as an interface for Browser integration. This would come very hands with the feature #40 so you could enable an easy flow to collect bookmarsk and to publish them.

Thank you in advance.

**Comment by RadhiFadlillah** [comment]
Hi @julianxhokaxhiu, thanks for using this app.

For REST API, `shiori` already have it with following endpoints :

```
POST   "/api/login"     // Login
GET    "/api/bookmarks" // Fetch bookmarks
POST   "/api/bookmarks" // Save new bookmark
PUT    "/api/bookmarks" // Update bookmark
DELETE "/api/bookmarks" // Delete bookmarks
```

For browser extension, I'm planning to do it in the future. However, I don't have any experience doing it before, so for now I will focus on fixing bug and make sure `shiori` is stable enough to use. Once that done, I will start doing extension for browser.

**Comment by mipmip** [comment]
👍

**Comment by kozko2001** [comment]
Hey @RadhiFadlillah  @mipmip 

I'm moving all my workflow from wallabag to shiori :) and since I needed some extension to have 
the same functionality I just made a simple one. 

https://github.com/kozko2001/shiori-extension

It's really basic, just allow you to login and bookmark the current url but for me is enough, if you want to contribute or maybe you think it's better to transfer the ownership just tell me!

**Comment by RadhiFadlillah** [comment]
Hi guys. Right now the [web extension](https://github.com/go-shiori/shiori-web-ext) is already available. It's still in beta and only tested in Firefox 59+, but it should also works in Chrome.

With that said, I will close this issue for now. Any issue about extension could be opened on its own repo.
