### ISSUE TITLE
DB not created in brand new installation/build (sqlite)

### ISSUE THREAD

**Issue by phiatlux** [go-shiori/shiori#417]
I am probably doing sth wrong, but it looks like that in a brand new shiori installation/build, the db is not created.
I mean, I'm getting a **failed to fetch accounts: SQL logic error: no such table: account (1) (500)** when I'm trying to login, or 
**Failed to create ID: SQL logic error: no such table: bookmark (1)**, if I try to _shiori add_

**Comment by fmartingr** [comment]
Hey @phiatlux, can you run `shiori migrate` and check if that creates the tables properly? I added migrations to SQLIte in the latest development version but forgot to add the explanation in the readme, mostly because I need to revamp the docs.

**Comment by phiatlux** [comment]
@fmartingr you're right!  `shiori migrate` is all it takes. Thank you very much

.

**Comment by wgetgoose** [comment]
Just wanted to update that this issue persists in docker as well.

**Comment by fmartingr** [comment]
> Just wanted to update that this issue persists in docker as well.

You need to run `shiori migrate` for fresh installations and upgrades as well when running shiori under containers.

I've added a mention to this [in the docs](https://github.com/go-shiori/shiori/blob/master/docs/Usage.md#running-migrations).

**Comment by fmartingr** [comment]
> I did not want to open a new issue, so I am sorry for the resurrection. I tried to deploy on Heroku and this "migrate" thing is kind of annoying. Also, you can't choose which port to listen to on Heroku, so I changed the Dockerfile like this.

If I recall correctly, Heroku supports a special release phase for this kind of stuff, you can have a `release` dyno running the one-off migration command instead of running them on the Dockerfile (which it may not work depending on the situation). I'm not sure what the best solution would be for the port issue, since that is specific to Heroku.

**Comment by kaimoe** [comment]
> You need to run `shiori migrate` for fresh installations and upgrades as well when running shiori under containers.

In my experience this was not possible. The container was being instantly killed due to the following failure because the `shiori.db` file did not exist:
```
goroutine 1 [running]:
github.com/jmoiron/sqlx.MustConnect(...)
        /home/runner/go/pkg/mod/github.com/jmoiron/sqlx@v1.3.5/sqlx.go:654
github.com/go-shiori/shiori/internal/database.OpenSQLiteDatabase({0xc000024468, 0x15fc350})
        /home/runner/work/shiori/shiori/internal/database/sqlite.go:27 +0xaa
github.com/go-shiori/shiori/internal/cmd.openSQLiteDatabase()
        /home/runner/work/shiori/shiori/internal/cmd/root.go:117 +0x6a
github.com/go-shiori/shiori/internal/cmd.openDatabase()
        /home/runner/work/shiori/shiori/internal/cmd/root.go:111 +0x79
github.com/go-shiori/shiori/internal/cmd.preRunRootHandler(0xc0001d4c80, {0xbbd9a8, 0x0, 0x0})
        /home/runner/work/shiori/shiori/internal/cmd/root.go:64 +0x116
github.com/spf13/cobra.(*Command).execute(0xc0001d4c80, {0x15fbd98, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:840 +0x50a
github.com/spf13/cobra.(*Command).ExecuteC(0xc000155400)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
        /home/runner/work/shiori/shiori/main.go:19 +0x1e
```

Because of this, there was no way to run the migrate script, as it is impossible to run `exec` on a stopped container (not to mention, if the `--rm` flag was used as recommended, the container was being instantly destroyed). Also, the recommended command `docker run containername shiori migrate` was invalid, as `docker run` doesn't (to my knowledge) operate on containers (`Unable to find image 'shiori:latest' locally` etc). The "correct" version would be `docker run --rm -v $(pwd):/shiori ghcr.io/go-shiori/shiori migrate`, but this still didn't actually create the database file either.

The only solution that worked for me was to `touch shiori.db`. Perhaps some simple logic to create the file if it doesn't exist should be included?
