### ISSUE TITLE
error ： add url=https://www.eknori.de/tags/console/

### ISSUE THREAD

**Issue by pope-L** [go-shiori/shiori#421]
error ： add url=https://www.eknori.de/tags/console/

**Comment by hulb** [comment]
I have a look at the page using the latest firefox browser. The browser shows this page is readble, but when I toggle the reader view, it doesn't work as expectly. Since `shiori` handles the readability of a page as the same as firefox reader view function, I think there is no work around now to fix this until firefox makes it right.

**Comment by fmartingr** [comment]
Hey @pope-L , can you be more specific about the error you're experiencing?
