### ISSUE TITLE
Isue with archive for Github web page

### ISSUE THREAD

**Issue by juev** [go-shiori/shiori#444]
Hello,

When I saves Github page to shiori I got unreadable result.

I saved html page for original and archive. Whats wrong?

[archive.zip](https://github.com/go-shiori/shiori/files/8998260/archive.zip)

As I can see, we have duplicate `meta character`, wrong `meta name="optimizely-datafile"`, many js files was merged to one file.

Why you changed canonical url?

```css
<link rel="canonical" href="https-github.com-milgradesec-ddns" data-pjax-transient=""/>
```

As I can see this pages have many difference on body. Whats wrong?

**Comment by fmartingr** [comment]
Hey @juev, we currently use [warc](https://github.com/go-shiori/warc) to archive websites, but there's plans to move to [obelisk](https://github.com/go-shiori/obelisk) (#353) which would hopefully fix some archiving issues, I can't say for sure why it's doing what you mention right now (until I hop on that task) but since we're archiving sites some procesing needs to be done and maybe some data treatment breaks some headers.

This is a low priority at the moment until we finish up with #353. And if we don't end up migrating to that we could take a look at that in WARC.
