### ISSUE TITLE
failed to fetch accounts: SQL logic error: no such table: account (1) (500)

### ISSUE THREAD

**Issue by rbdevr** [go-shiori/shiori#447]
shiori 1.5.3 returns error for blank database

failed to fetch accounts: SQL logic error: no such table: account (1) (500)

**Comment by hulb** [comment]
you need to run `migrate` command first before you run `serve`

**Comment by rbdevr** [comment]
I did. running migrate returns erro no change.

And running serve gives me the logging screen and the error in the main post.

**Comment by hulb** [comment]
What db do you use?I try to reproduce the issue with SQLite yesterday but after I executed migrate cmd things worked fine. What's the steps to reproduce the problem?

**Comment by ofersadan85** [comment]
@hulb I also have this error on first use. My steps to reproduce:

    docker run -d --rm --name shiori -p 8080:8080 -v shiori:/shiori ghcr.io/go-shiori/shiori

Then I go to http://localhost:8080 and login with username: shiori, password: gopher and I get the same error as above

Looking at the created volume, looks like there's one file there named `shiodi.db` with a size of 0 bytes

Running this command fixed it:

    docker exec -it shiori shiori migrate

**Comment by hulb** [comment]
> @hulb I also have this error on first use. My steps to reproduce:
> 
> 
> 
>     docker run -d --rm --name shiori -p 8080:8080 -v shiori:/shiori ghcr.io/go-shiori/shiori
> 
> 
> 
> Then I go to http://localhost:8080 and login with username: shiori, password: gopher and I get the same error as above
> 
> 
> 
> Looking at the created volume, looks like there's one file there named `shiori.db` with a size of 0 bytes
> 
> 
> 
> Running this command fixed it:
> 
> 
> 
>     docker exec -it shiori shiori migrate
> 
> 
> 
> But this is undocumented as far as I can see, so I don't know if this is expected behavior
> 
> 

Your situation is expected because migrate wouldn't be executed before serve command in docker image. The process of server startup in container will be updated to avoid issue like that in the future.

**Comment by rbdevr** [comment]
running on linux 64bit under apache
extract to: /opt/shiori
run: ./shiori serve -p 8523 --webroot /shiori
access http://localhost/shiori
user admin pass gopher press login 
returns failed to fetch accounts: SQL logic error: no such table: account (1) (500)

run ./shiori migrate
returns erro no change

**Comment by CaptainKraft** [comment]
I had a similar issue. When I ran shiori as a systemd service, the directory for shiori files was set differently than when running the command myself.

This problem can come up if shiori is looking in the wrong directory for the database files. Ensure that your env variable is set correctly.

**Comment by rbdevr** [comment]
what environment variable are you talking about? could you be more specific?

**Comment by hulb** [comment]
> This problem can come up if shiori is looking in the wrong directory for the database files. Ensure that your env variable is set correctly.

Yes, it maybe the reason. @rbdevr you can try to set a environment variable `SHIORI_DIR` before you execute any shiori command. The variable is to tell shiori where the db file(if you use default sqlite as your database) and archive data should be.

**Comment by rbdevr** [comment]
unfortunately set SHIORI_DIR didnt change anything.

**Comment by hulb** [comment]
@rbdevr I tried to reproduce your issue in a alpine docker container, here is my steps:
1. run a container with `docker run -it --rm -p 8000:8000 docker.io/library/alpine /bin/sh`
2. download shiori v1.5.3 release to `/opt`, extract it in `/opt`
3. run `./shiori serve -p 8000--webroot /shiori`
4. open browser and access `http://localhost:8000/shiori`, then I can seee a login page with some css style broken due to #445 , but login still functional
5. enter username and password to login, I got the err `failed to fetch accounts: SQL logic error: no such table: account (1) (500)`
6. back into the container and execute `./shiori migrate` at `/opt`
7. login again in browser, and login successfully

It seeems no problem, can you tell more details of how your steps look like ?

**Comment by fmartingr** [comment]
I've tried to reproduce this myself with the provided commands, and migration woks as expected:
1) `docker run -d --rm --name shiori -p 8080:8080 -v shiori:/shiori ghcr.io/go-shiori/shiori` This runs the server, an SQL on login cause database files are not created/migrated.
2) `docker run --rm --name shiori-migrate -v shiori:/shiori ghcr.io/go-shiori/shiori migrate` Running migration command as a separate container (no need for daemon, ports, etc, but use same volume configuration)

After #2 login page and shiori works as expected.

This is the workflow I use for some self-hosted software I have, I have setup the configuration in ansible, and when the image label changes (version upgrade) two containers are created, first the migrations and then the service itself. This can be solved in kubernetes with an init container, but I'm against running the migrations each time shiori is invoked.

I've also tested this with the 1.5.3 binary on a fresh ubuntu container and it worked after the migration:

```
root@5fb255862ffe:/# wget https://github.com/go-shiori/shiori/releases/download/v1.5.3/shiori_1.5.3_Linux_x86_64.tar.gz
[...]
2022-07-16 07:39:21 (31.3 MB/s) - 'shiori_1.5.3_Linux_x86_64.tar.gz' saved [7763741/7763741]
root@5fb255862ffe:/# tar xvzf shiori_1.5.3_Linux_x86_64.tar.gz
LICENSE
README.md
shiori
root@5fb255862ffe:/# mkdir -p opt/shiori
root@5fb255862ffe:/# mv shiori /opt/shiori/
root@5fb255862ffe:/# cd /opt/shiori/
root@5fb255862ffe:/opt/shiori# ./shiori add https://github.com
Failed to create ID: SQL logic error: no such table: bookmark (1)
root@5fb255862ffe:/opt/shiori# ./shiori migrate
root@5fb255862ffe:/opt/shiori# ./shiori migrate
Error during migration: no change
root@5fb255862ffe:/opt/shiori# ./shiori add asdasd
Failed to clean URL: URL is not valid
root@5fb255862ffe:/opt/shiori# ./shiori add https://github.com
Downloading article...

1. GitHub: Where the world builds software
   > https://github.com
   + GitHub is where over 83 million developers shape the future of software, together. Contribute to the open source community, manage your Git repositories, review code like a pro, track bugs and feat...
```

@rbdevr Is your database file in [this comment's example](https://github.com/go-shiori/shiori/issues/447#issuecomment-1179364757) created? is it zero bytes? There is something weird going on there.

Regarding the migration procedure, this is specified [in the documentation](https://github.com/go-shiori/shiori/blob/master/docs/Usage.md#running-migrations). But since it doesn't seem clear enough we may need to explain everything a little bit better.

**Comment by rbdevr** [comment]
> @rbdevr I tried to reproduce your issue in a alpine docker container, here is my steps:
> 
> 1. run a container with `docker run -it --rm -p 8000:8000 docker.io/library/alpine /bin/sh`
> 2. download shiori v1.5.3 release to `/opt`, extract it in `/opt`
> 3. run `./shiori serve -p 8000--webroot /shiori`
> 4. open browser and access `http://localhost:8000/shiori`, then I can seee a login page with some css style broken due to [Server error with CSS files with new version #445](https://github.com/go-shiori/shiori/issues/445) , but login still functional
> 5. enter username and password to login, I got the err `failed to fetch accounts: SQL logic error: no such table: account (1) (500)`
> 6. back into the container and execute `./shiori migrate` at `/opt`
> 7. login again in browser, and login successfully
> 
> It seeems no problem, can you tell more details of how your steps look like ?

We are in sync until item 6.

I added "export SHIORI_DIR=/opt/Shiori" 

run shiori migrate always returns:

"Error during migration: no change[/opt/Shiori]"

 the database size is /opt/Shiori/shiori.db is 92KB

when I try to add a link using shiori add {url} it returns 

"Failed to save bookmark: constraint failed: UNIQUE constraint failed: bookmark.url (2067)"

**Comment by hulb** [comment]
> "Failed to save bookmark: constraint failed: UNIQUE constraint failed: bookmark.url (2067)"

It means the url have been already added to shiori. Repeated add a url is not allowed.

**Comment by m3nu** [comment]
Running the `migrate` command worked for me too. Could be documented and mentioned in the release log.

**Comment by fmartingr** [comment]
> Running the `migrate` command worked for me too. Could be documented and mentioned in the release log.

You're right. I've added this in the 1.5.3 release notes: https://github.com/go-shiori/shiori/releases/tag/v1.5.3

**Comment by m3nu** [comment]
Thanks! Would be even better to have the Docker container run it automatically, if needed. I'm assuming this command is idempotent.

**Comment by kklot** [comment]
this also happens when using `--portable` option. What should I add to the exe's directory to run in portable mode?
Thanks,

**Comment by Katarn** [comment]
> this also happens when using `--portable` option. What should I add to the exe's directory to run in portable mode?

First run

```bash
shiori migrate --portable
```

I described the non-obviousness of this problem in #473

**Comment by AIndoria** [comment]
Can someone tell me how this was 'fixed?' This still happens when installing the latest docker version or doing a docker build.

Running `docker exec -it shiori shiori migrate` does absolutely nothing.
