### ISSUE TITLE
Questions about API

### ISSUE THREAD

**Issue by kzshantonu** [go-shiori/shiori#586]
Hi, I'm trying to make a shortcut in android with HTTP shortcuts app and I have some questions:

```
{
	"username": "shiori",
	"password": "gopher",
	"remember": true,
	"owner": true
}
```

1. What exactly does `owner` mean? What does it do?

2. Is there a way to make `sessionId` persistent? Like static API keys? I find that even with `remember: true`, sessions don't persist after the server is restarted

**Comment by fmartingr** [comment]
1. `owner` is the internal representation of the user that owns the bookmarks. When is true, it means that it has read/write access to the bookmarks, tags, etc. Otherwise it would be read-only.
2. Not at the moment, I'm working on that here: https://github.com/go-shiori/shiori/pull/497 Sessions are currently persisted in memory, that's why a restart invalidates them.

**Comment by kzshantonu** [comment]
Thanks. Noted
