### ISSUE TITLE
Feature Request:  add support for Nextcloud Bookmarks via REST API

### ISSUE THREAD

**Issue by sunjam** [go-shiori/shiori#60]
It would awesome if Shiori could sync with the open source [Nextcloud Bookmarks app](https://github.com/nextcloud/bookmarks) and make use of the browser extensions.  Should be do-able when #41 is integrated.  Also referenced in [Nextcloud Bookmarks issue #438](https://github.com/nextcloud/bookmarks/issues/438)

**Comment by arendtio** [comment]
@sunjam I wonder how that is supposed to work. Do you want to use the Shiori server as an adapter in front of the Nextcloud API?!? Its like putting the motor of a [Trabant](https://en.wikipedia.org/wiki/Trabant) into a Ferrari.

Don't get me wrong. I am myself a heavy Nextcloud user and would love to to see the features of Shiori in the Nextcloud bookmark app. In fact, the sorry state of the Nextcloud bookmark app is what makes me want to use Shiori. I just don't know how those two are supposed to work together.

Can you please elaborate how the setup is supposed to work?

**Comment by marcelklehr** [comment]
I believe the idea is to use shiori as an offline-capable app that syncs with nextcloud bookmarks, so you can access your bookmarks elsewhere via nextclouds sync API.

Also, (as a little teaser) I hope you'll enjoy some upcoming major improvements of the bookmarks app ;)

**Comment by arendtio** [comment]
@marcelklehr it is nice to hear you are working on improving the Nextcloud Bookmarks app.

Off-Topic: What I am missing most in the current version (0.11.0) of the Nextcloud Bookmarks app, is some filter field which lets you filter the title and URL of the bookmark (similar to what Shiori does, maybe even with some fuzzy logic e.g. https://github.com/farzher/fuzzysort ).

Features like the cache in Shiori are nice too, but I can understand that those are not easy to implement as you need either a lot of storage or some smart logic to filter the important parts (which in turn probably sometimes fails). So I am totally okay with running an extra service if you want to store offline copies of websites.

**Comment by marcelklehr** [comment]
@arendtio thanks for your feedback! And stay tuned ;)

**Comment by RadhiFadlillah** [comment]
Hi guys, sorry for late, late reply.

Unfortunately, I don't think I will do this. There are several reasons, however the main reason is I lack the time to do it.

Right now I don't really have as many free time as before. Therefore, right now I just want to focus on the main purpose of Shiori, i.e. bookmark and archiving a web page. Fortunately, since the latest commit, I believe Shiori is quite good at those, thanks to `go-readability` for caching and `pkg/warc` for archiving.

With that said, for now I'm planning to do feature-freeze for Shiori so I can focus on improving its core abilities and fix the bugs.
