### ISSUE TITLE
eBooks - Open questions about HowTo and missing pictures

### ISSUE THREAD

**Issue by rmayergfx** [go-shiori/shiori#682]
## Data
- **Shiori version**:  v1.5.5
- **Database Engine**: 
- **Operating system**: 
- **CLI/Web interface/Web Extension**: 0.8.7

CLI and Web Extension does not show me any default option to create eBooks by default. I can only create an eBook by "Update archive"
![grafik](https://github.com/go-shiori/shiori/assets/105392164/bd27062a-1eca-4365-ae2f-988ea81b4279)
So any explanation or update in the settings would be great. shiori was setup in a fresh docker on synology, so i think it is all up to date.

btw. inside the created eBook all pictures are missing.

plz feel free to test with this page: https://www.maerklin-messagewagons.com/de

**Comment by rmayergfx** [comment]
Calibre is used to read the eBooks. After saving the ebook it shows a too small size, 16K so no pictures can be inside and also there is a cross for missing picture.

**Comment by rmayergfx** [comment]
@Monirzadeh 
thx for explanation. thats right, readable has no pictures, so eBook is exactly like the readable version.
Sorry, but i think the archived Version should be used to create eBooks with all pictures. In my case eBook from readable version is useless to me.

**Comment by fmartingr** [comment]
Ebooks are generated from the readable version since it should be a simplified version and "content-only" from the saved bookmark. Having an ebook from an archive doesn't make much sense since you would have a way better output just saving the page as PDF directly, since and aPub layout should be simple for readers. 
Besides, the website you propose doesn't have much content to work with anyway (at least right now, but since it says sold out maybe it had more content previously?).

If you still want epub from archives, please feel free [to submit a feature request](https://github.com/go-shiori/shiori/discussions/categories/feature-requests).

Regarding the UX on ebook generation, it will be worked in #659. Right now we are in the middle of an API overhaul and most of the features/improvements will happen once we refactor that part of the code.

**Comment by fmartingr** [comment]
> it is valid we should add option to generate ebook from cli and default option in settings

Can you create the separate issues we need from this one so we can close it? I'd rather have some issues as action items we can put into versions rather than vague descriptions.
