### ISSUE TITLE
403 forbidden request forbidden by administrative rules

### ISSUE THREAD

**Issue by Tataukee** [go-shiori/shiori#712]
Unable to save [this article](https://actu.fr/normandie/rouen_76540/rouen-des-familles-au-tribunal-pour-defendre-l-ecole-a-la-maison-on-nous-taxe-de-separatistes_59971016.html) , the link either displaying the error message indicated in the title of this issue or opening the link to its original source page .
The article is easily saved to other read later / bookmarks apps .

**Comment by Tataukee** [comment]
Thank you . 
Im using Portainer stack to deploy Shiori .
Do you have an idea how to deploy/integrate [go-readability](https://github.com/go-shiori/go-readability) ?

**Comment by Tataukee** [comment]
yes I do actually have a similar problem with [another site](https://www.names.org/n/huset/about) getting this error this time : Please enable JS and disable any ad blocker .

**Comment by fmartingr** [comment]
The first article is failing because of the unrecognised user agent we send when downloading a page:

```
$ curl --user-agent "Shiori/2.0.0 (+https://github.com/go-shiori/shiori)" https://actu.fr/normandie/rouen_76540/rouen-des-familles-au-tribunal-pour-defendre-l-ecole-a-la-maison-on-nous-taxe-de-separatistes_59971016.html
<html><body><h1>403 Forbidden</h1>
Request forbidden by administrative rules.
</body></html>
```

The second one is probably failing because we do not use a browser for archiving, so javascript is not executed when doing archive. That page may have something in place to detect JS in the browser or something like that.

This raises the old issue of... should we use a browser to create archives? I have, like with everything, ideas around my head, but nothing specific nor in the roadmap at the moment.

The idea of allowing plugins into Shiori is starting to make more sense to me, but it would be an enormous effort to put through, considering there are only two active contributors at the moment.
