### ISSUE TITLE
Hierarchy / Folders

### ISSUE THREAD

**Issue by marco-trovato** [go-shiori/shiori#774]
## Data
- **Shiori version**: 1.5.5
- **Database Engine**: default
- **Operating system**: Linux
- **CLI/Web interface/Web Extension**: CLI + web interface

## Describe the bug / actual behavior
I imported my 20 years of bookmarks in hierarchy folders, but the result is a mess of 350 pages of sequentially listed bookmarks URLs with TAGs. It's impossible to use or find anything like this.

## Expected behavior
I expected to browse my bookmarks as a "tree view", or as a "Outliner".

## To Reproduce
1. Use the program normally
2. There is no "add folder" option to create a hierarchy
3. Import bookmarks with folders: same problem, all URLs get mashed together with TAGs

## Notes
I have tried dozen of programs and this is the best and most portable bookmark manager i have found, i love it ❤️

**Comment by fmartingr** [comment]
Hey @marco-trovato! Thank for your report. There's a feature request for bookmark folders here: https://github.com/go-shiori/shiori/discussions/371 if you could share your opinion (and maybe some screenshots on how your UI looks since you have that much data) it would be nice. I'm closing this to focus the conversation in one place.

**Comment by marco-trovato** [comment]
I don't understand, why is this flagged as done if i don't see any "add folder" option in the last version?
